### ISSUE TITLE
TypeError: Can't instantiate abstract class Hotmart without an implementation for abstract method 'format_account_products'

### ISSUE THREAD

**Issue by Chaoscontrol** [katomaro/katomart#27]
1. Added a Hotmart account
2. Go to "Cursos", choose Hotmart, select the account, and click "Inicializar Conta Selecionada"
3. Page reloads, but nothing happens. 
4. CMD shows this error:
```
127.0.0.1 - - [09/Apr/2024 18:28:51] "GET /api/agreement HTTP/1.1" 200 -
127.0.0.1 - - [09/Apr/2024 18:28:51] "POST /api/save_user_state HTTP/1.1" 200 -
127.0.0.1 - - [09/Apr/2024 18:28:54] "GET /api/agreement HTTP/1.1" 200 -
127.0.0.1 - - [09/Apr/2024 18:28:54] "GET /api/courses HTTP/1.1" 400 -
127.0.0.1 - - [09/Apr/2024 18:28:54] "GET /api/agreement HTTP/1.1" 200 -
127.0.0.1 - - [09/Apr/2024 18:28:55] "GET /api/platforms HTTP/1.1" 200 -
127.0.0.1 - - [09/Apr/2024 18:28:57] "GET /api/get_accounts?platform_id=1 HTTP/1.1" 200 -
127.0.0.1 - - [09/Apr/2024 18:28:59] "POST /api/select_account HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\katomart\katomart.py", line 286, in select_account
    selected_platform_instance = platform_class(
                                 ^^^^^^^^^^^^^^^
TypeError: Can't instantiate abstract class Hotmart without an implementation for abstract method 'format_account_products'
127.0.0.1 - - [09/Apr/2024 18:29:00] "GET /api/agreement HTTP/1.1" 200 -
127.0.0.1 - - [09/Apr/2024 18:29:00] "GET /api/get_accounts?platform_id=1 HTTP/1.1" 200 -
127.0.0.1 - - [09/Apr/2024 18:29:00] "GET /api/courses HTTP/1.1" 400 -
127.0.0.1 - - [09/Apr/2024 18:29:00] "GET /api/agreement HTTP/1.1" 200 -
127.0.0.1 - - [09/Apr/2024 18:29:00] "GET /api/platforms HTTP/1.1" 200 -
```

**Comment by Chaoscontrol** [comment]
Fixed after a change notified on telegram.
