### ISSUE TITLE
[BUG] Não baixa vídeo do hotmart se tem vídeo privado do youtube

### ISSUE THREAD

**Issue by mauroobento** [katomaro/katomart#43]
Opa, 

Estou tentando baixar um curso da Hotmart, mas quando o script chega em uma determinada parte, onde dentro das descrições do vídeo tem um link para um vídeo (privado) no youtube, ele não consegue baixar, mesmo desmarcando a opção de baixar youtube nas configurações. Percebi que usa o sqlite para poder guardar as informações, então deletei o arquivo sqlite e restartei o script (para ter certeza que não teria ""lixo"" da configuração anterior) e, mesmo assim, não adiantou de nada. O script tenta, de toda forma, baixar o vídeo privado e não segue adiante. Nem mesmo se eu desmarcar tal aula para ele poder ""pular"", não vai, tenta baixar de qualquer forma. Segue o erro que estoura no terminal quando tenta baixar. Troquei o ID do vídeo do youtube por `{id}` por questões de segurança. 

```bash
[youtube] Extracting URL: https://www.youtube.com/watch?v={id}
[youtube] {id}: Downloading webpage
[youtube] {id}: Downloading ios player API JSON
ERROR: [youtube] {id}: Private video. Sign in if you've been granted access to this video
Exception in thread Thread-28 (download_account_downloadable_products):
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/yt_dlp/extractor/youtube.py", line 4248, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/opt/homebrew/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1257, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] {id}: Private video. Sign in if you've been granted access to this video

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/obento/Downloads/kato/modules/downloaders/main_downloader.py", line 239, in download_account_downloadable_products
    self.scan_text_content(lesson_files['text_content'], lesson_path)
  File "/Users/obento/Downloads/kato/modules/downloaders/main_downloader.py", line 309, in scan_text_content
    if self.resolve_linked_player(video_url, save_path, media_count=media_counter):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/obento/Downloads/kato/modules/downloaders/main_downloader.py", line 323, in resolve_linked_player
    self.download_ytdlp_media(link.group(0), referer=self.current_content_url, save_path=save_path, media_index=media_count)
  File "/Users/obento/Downloads/kato/modules/downloaders/main_downloader.py", line 641, in download_ytdlp_media
    ytdlp.download([url])
  File "/opt/homebrew/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3583, in download
    self.__download_wrapper(self.extract_info)(
  File "/opt/homebrew/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3558, in wrapper
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1595, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1624, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/opt/homebrew/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1073, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/opt/homebrew/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1012, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] {id}: Private video. Sign in if you've been granted access to this video
```

Segue um print da tela de configuração

![image](https://github.com/katomaro/katomart/assets/161063916/4353f8e9-0e41-4016-bb9a-68ac68472517)

O que posso fazer para conseguir baixar o curso todo? Mesmo pulando todo o módulo não passa...

**Comment by katomaro** [comment]
Acabei de trocar a forma de download de manual para ytdlp em todos os vídeos, vou por um try:except para ignorar em caso de vídeo privado (que é deveras estranho), obrigado por avisar sobre essa possibilidade.

**Comment by mauroobento** [comment]
O mais estranho é o script não pular módulo/aula que foram devidamente desmarcadas para não serem baixadas. Eu cliquei várias vezes para ele não baixar estas aulas e o script apenas ignorou por completo. Não sei se tem algo a ver ou se isto pode te ajudar de alguma forma a encontrar outro erro / bug... 

Irei atualizar aqui o script e volto com update

**Comment by mauroobento** [comment]
Testei aqui e tá legal agora... Porém, mesmo se o vídeo do youtube NÃO é privado, ele não baixa... Copiei o link aqui do youtube e baixou sem o menor problema em um outro aplicativo... Tem como fazer com que o script entenda quando é um vídeo privado e pula ele e o que não for, baixe?
