### ISSUE TITLE
TypeError: unsupported operand type(s) for

### ISSUE THREAD

**Issue by spindrm** [katomaro/katomart#57]
C:\katomart-master>python katomart.py
Traceback (most recent call last):
  File "C:\katomart-master\katomart.py", line 17, in <module>
    from modules.accounts.hotmart import Hotmart
  File "C:\katomart-master\modules\accounts\hotmart.py", line 3, in <module>
    from .abstract import Account
  File "C:\katomart-master\modules\accounts\abstract.py", line 12, in <module>
    class Account(ABC):
  File "C:\katomart-master\modules\accounts\abstract.py", line 129, in Account
    def format_account_products(self, product_id: int | str | None = None, product_info: dict = None):
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by katomaro** [comment]
Atualiza a versao instalado do python.
